import { type Product } from './types'

export const mockProducts: Product[] = [
  {
    id: '1',
    nameEn: 'Organic Acacia Honey',
    nameFr: 'Miel Organique Acacia',
    nameAr: 'عسل الأكاسيا العضوي',
    descriptionEn: 'Pure organic acacia honey with delicate floral notes',
    descriptionFr: 'Miel organique pur d\'acacia aux notes florales délicates',
    descriptionAr: 'عسل أكاسيا عضوي نقي برائحة زهرية رقيقة',
    price: 25.99,
    image: '/organic-acacia-honey.jpg',
    category: 'organic-honey',
    subcategory: 'Acacia',
  },
  {
    id: '2',
    nameEn: 'Organic Eucalyptus Honey',
    nameFr: 'Miel Organique Eucalyptus',
    nameAr: 'عسل الكافور العضوي',
    descriptionEn: 'Smooth eucalyptus honey with soothing properties',
    descriptionFr: 'Miel eucalyptus lisse aux propriétés apaisantes',
    descriptionAr: 'عسل الكافور الناعم بخصائص مهدئة',
    price: 23.99,
    image: '/organic-eucalyptus-honey.jpg',
    category: 'organic-honey',
    subcategory: 'Eucalyptus',
  },
  {
    id: '3',
    nameEn: 'Multi-flower Organic Honey',
    nameFr: 'Miel Organique Multi-fleur',
    nameAr: 'عسل متعدد الأزهار العضوي',
    descriptionEn: 'Complex blend of wildflower honey from Tunisian meadows',
    descriptionFr: 'Mélange complexe de miel de fleurs sauvages des prairies tunisiennes',
    descriptionAr: 'مزيج معقد من عسل الأزهار البرية من المراعي التونسية',
    price: 21.99,
    image: '/wildflower-honey.png',
    category: 'organic-honey',
    subcategory: 'Multi-fleur',
  },
  {
    id: '4',
    nameEn: 'Honey & Ginger Mix',
    nameFr: 'Miel & Gingembre',
    nameAr: 'عسل والزنجبيل',
    descriptionEn: 'Warming blend of honey with fresh ginger',
    descriptionFr: 'Mélange réchauffant de miel avec gingembre frais',
    descriptionAr: 'مزيج دافئ من العسل مع الزنجبيل الطازج',
    price: 19.99,
    image: '/honey-ginger.jpg',
    category: 'mixes',
    subcategory: 'Miel & Gingembre',
  },
  {
    id: '5',
    nameEn: 'Honey & Lemon Mix',
    nameFr: 'Miel & Citron',
    nameAr: 'عسل والليمون',
    descriptionEn: 'Refreshing blend of honey with lemon',
    descriptionFr: 'Mélange rafraîchissant de miel avec citron',
    descriptionAr: 'مزيج منعش من العسل مع الليمون',
    price: 19.99,
    image: '/honey-lemon.jpg',
    category: 'mixes',
    subcategory: 'Miel & Citron',
  },
  {
    id: '6',
    nameEn: 'Bsisa Honey Cereal',
    nameFr: 'Bsisa Miel',
    nameAr: 'بسيسة عسل',
    descriptionEn: 'Traditional Tunisian honey and grain mix for energy',
    descriptionFr: 'Mélange traditionnel tunisien de miel et de céréales pour l\'énergie',
    descriptionAr: 'مزيج تقليدي تونسي من العسل والحبوب للطاقة',
    price: 15.99,
    image: '/bsisa-grain.jpg',
    category: 'bsisa',
  },
  {
    id: '7',
    nameEn: 'Pure Bee Pollen',
    nameFr: 'Pollen d\'Abeille Pur',
    nameAr: 'حبوب اللقاح النقية',
    descriptionEn: 'Premium bee pollen rich in nutrients',
    descriptionFr: 'Pollen d\'abeille premium riche en nutriments',
    descriptionAr: 'حبوب لقاح النحل الممتازة الغنية بالعناصر الغذائية',
    price: 29.99,
    image: '/bee-pollen.png',
    category: 'diverse',
    subcategory: 'Pollen',
  },
  {
    id: '8',
    nameEn: 'Natural Propolis',
    nameFr: 'Propolis Naturelle',
    nameAr: 'البروبوليس الطبيعي',
    descriptionEn: 'Pure natural propolis for wellness',
    descriptionFr: 'Propolis naturelle pure pour le bien-être',
    descriptionAr: 'بروبوليس طبيعي نقي للعافية',
    price: 34.99,
    image: '/propolis.jpg',
    category: 'diverse',
    subcategory: 'Propolis',
  },
]
